name: Cat Facts Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the bot
        run: |
          python cat.py
